import { db } from '@/db';
import { couriers } from '@/db/schema';

async function main() {
    const sampleCouriers = [
        {
            name: 'Alex Chen',
            phone: '+1-212-555-0134',
            email: 'alex.chen@dryft.com',
            vehicleType: 'bike',
            status: 'available',
            currentLat: 40.7489,
            currentLng: -73.9680,
            rating: 4.8,
            totalDeliveries: 456,
            createdAt: new Date('2024-08-15').toISOString(),
        },
        {
            name: 'Sofia Rodriguez',
            phone: '+1-212-555-0287',
            email: 'sofia.rodriguez@dryft.com',
            vehicleType: 'scooter',
            status: 'available',
            currentLat: 40.7614,
            currentLng: -73.9776,
            rating: 4.9,
            totalDeliveries: 623,
            createdAt: new Date('2024-07-22').toISOString(),
        },
        {
            name: 'Omar Hassan',
            phone: '+1-212-555-0391',
            email: 'omar.hassan@dryft.com',
            vehicleType: 'bike',
            status: 'busy',
            currentLat: 40.7282,
            currentLng: -73.9942,
            rating: 5.0,
            totalDeliveries: 789,
            createdAt: new Date('2024-06-10').toISOString(),
        },
        {
            name: 'Nina Patel',
            phone: '+1-212-555-0445',
            email: 'nina.patel@dryft.com',
            vehicleType: 'scooter',
            status: 'available',
            currentLat: 40.7580,
            currentLng: -73.9855,
            rating: 4.7,
            totalDeliveries: 334,
            createdAt: new Date('2024-09-05').toISOString(),
        },
        {
            name: 'Carlos Gomez',
            phone: '+1-212-555-0598',
            email: 'carlos.gomez@dryft.com',
            vehicleType: 'car',
            status: 'available',
            currentLat: 40.7128,
            currentLng: -73.9950,
            rating: 4.6,
            totalDeliveries: 267,
            createdAt: new Date('2024-10-01').toISOString(),
        },
        {
            name: 'Ava Thompson',
            phone: '+1-212-555-0652',
            email: 'ava.thompson@dryft.com',
            vehicleType: 'bike',
            status: 'available',
            currentLat: 40.7831,
            currentLng: -73.9712,
            rating: 4.9,
            totalDeliveries: 541,
            createdAt: new Date('2024-07-18').toISOString(),
        },
        {
            name: 'Marcus Johnson',
            phone: '+1-212-555-0723',
            email: 'marcus.johnson@dryft.com',
            vehicleType: 'scooter',
            status: 'offline',
            currentLat: 40.7359,
            currentLng: -73.9911,
            rating: 4.8,
            totalDeliveries: 412,
            createdAt: new Date('2024-08-28').toISOString(),
        },
        {
            name: 'Priya Singh',
            phone: '+1-212-555-0856',
            email: 'priya.singh@dryft.com',
            vehicleType: 'scooter',
            status: 'available',
            currentLat: 40.7549,
            currentLng: -73.9840,
            rating: 5.0,
            totalDeliveries: 698,
            createdAt: new Date('2024-06-25').toISOString(),
        },
        {
            name: 'Daniel Kim',
            phone: '+1-212-555-0912',
            email: 'daniel.kim@dryft.com',
            vehicleType: 'car',
            status: 'available',
            currentLat: 40.7689,
            currentLng: -73.9640,
            rating: 4.7,
            totalDeliveries: 189,
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            name: 'Isabella Martinez',
            phone: '+1-212-555-1045',
            email: 'isabella.martinez@dryft.com',
            vehicleType: 'bike',
            status: 'available',
            currentLat: 40.7420,
            currentLng: -73.9896,
            rating: 4.9,
            totalDeliveries: 523,
            createdAt: new Date('2024-07-30').toISOString(),
        },
    ];

    await db.insert(couriers).values(sampleCouriers);
    
    console.log('✅ Couriers seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});