import { db } from '@/db';
import { drivers } from '@/db/schema';

async function main() {
    const sampleDrivers = [
        {
            name: 'John Smith',
            phone: '+1-212-555-0101',
            email: 'john.smith@dryft.com',
            vehicleType: 'sedan',
            licensePlate: 'ABC-1234',
            status: 'available',
            currentLat: 40.7489,
            currentLng: -73.9680,
            rating: 4.8,
            totalRides: 324,
            createdAt: new Date('2024-08-15').toISOString(),
        },
        {
            name: 'Maria Garcia',
            phone: '+1-212-555-0102',
            email: 'maria.garcia@dryft.com',
            vehicleType: 'suv',
            licensePlate: 'DEF-5678',
            status: 'available',
            currentLat: 40.7614,
            currentLng: -73.9776,
            rating: 4.9,
            totalRides: 412,
            createdAt: new Date('2024-07-22').toISOString(),
        },
        {
            name: 'David Johnson',
            phone: '+1-212-555-0103',
            email: 'david.johnson@dryft.com',
            vehicleType: 'sedan',
            licensePlate: 'GHI-9012',
            status: 'available',
            currentLat: 40.7580,
            currentLng: -73.9855,
            rating: 4.7,
            totalRides: 267,
            createdAt: new Date('2024-09-10').toISOString(),
        },
        {
            name: 'Sarah Lee',
            phone: '+1-212-555-0104',
            email: 'sarah.lee@dryft.com',
            vehicleType: 'sedan',
            licensePlate: 'JKL-3456',
            status: 'busy',
            currentLat: 40.7505,
            currentLng: -73.9934,
            rating: 5.0,
            totalRides: 489,
            createdAt: new Date('2024-06-05').toISOString(),
        },
        {
            name: 'Michael Brown',
            phone: '+1-212-555-0105',
            email: 'michael.brown@dryft.com',
            vehicleType: 'van',
            licensePlate: 'MNO-7890',
            status: 'available',
            currentLat: 40.7638,
            currentLng: -73.9731,
            rating: 4.6,
            totalRides: 198,
            createdAt: new Date('2024-10-12').toISOString(),
        },
        {
            name: 'Jennifer Wilson',
            phone: '+1-212-555-0106',
            email: 'jennifer.wilson@dryft.com',
            vehicleType: 'suv',
            licensePlate: 'PQR-2345',
            status: 'available',
            currentLat: 40.7423,
            currentLng: -73.9896,
            rating: 4.9,
            totalRides: 356,
            createdAt: new Date('2024-08-28').toISOString(),
        },
        {
            name: 'Robert Martinez',
            phone: '+1-212-555-0107',
            email: 'robert.martinez@dryft.com',
            vehicleType: 'sedan',
            licensePlate: 'STU-6789',
            status: 'available',
            currentLat: 40.7558,
            currentLng: -73.9865,
            rating: 4.5,
            totalRides: 143,
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            name: 'Lisa Anderson',
            phone: '+1-212-555-0108',
            email: 'lisa.anderson@dryft.com',
            vehicleType: 'sedan',
            licensePlate: 'VWX-0123',
            status: 'offline',
            currentLat: 40.7692,
            currentLng: -73.9547,
            rating: 4.8,
            totalRides: 278,
            createdAt: new Date('2024-07-18').toISOString(),
        },
        {
            name: 'James Taylor',
            phone: '+1-212-555-0109',
            email: 'james.taylor@dryft.com',
            vehicleType: 'suv',
            licensePlate: 'YZA-4567',
            status: 'available',
            currentLat: 40.7471,
            currentLng: -73.9969,
            rating: 4.7,
            totalRides: 301,
            createdAt: new Date('2024-09-25').toISOString(),
        },
        {
            name: 'Emily Davis',
            phone: '+1-212-555-0110',
            email: 'emily.davis@dryft.com',
            vehicleType: 'van',
            licensePlate: 'BCD-8901',
            status: 'available',
            currentLat: 40.7527,
            currentLng: -73.9772,
            rating: 4.9,
            totalRides: 445,
            createdAt: new Date('2024-06-30').toISOString(),
        },
    ];

    await db.insert(drivers).values(sampleDrivers);
    
    console.log('✅ Drivers seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});